# Generated by Django 4.2.7 on 2023-11-29 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packerman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('desc', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('img', models.TextField()),
                ('instructions', models.TextField()),
                ('needs_repair', models.BooleanField(default=False)),
                ('lost', models.BooleanField(default=False)),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='icon',
            new_name='img',
        ),
    ]
