# Generated by Django 4.2.7 on 2023-11-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packerman', '0002_items_rename_icon_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('event_type', models.CharField(max_length=200)),
            ],
        ),
    ]
