# Generated by Django 4.2.7 on 2023-11-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packerman', '0004_rename_user_users_user_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packed_date', models.DateField()),
                ('unpacked_date', models.DateField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='packerman.events')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_items', to='packerman.items')),
                ('packed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_user', to='packerman.users')),
                ('unpacked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpacking_user', to='packerman.users')),
            ],
        ),
    ]
