# Generated by Django 4.2.7 on 2023-11-29 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packerman', '0005_event_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Event_Items',
            new_name='Event_Item',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='User_Items',
            new_name='User_Item',
        ),
    ]
