# Generated by Django 4.2.7 on 2023-11-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packerman', '0007_alter_event_item_unpacked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_item',
            name='unpacked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unpacking_user', to='packerman.user'),
        ),
        migrations.AlterField(
            model_name='event_item',
            name='unpacked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_item',
            name='in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
