# Generated by Django 4.2.7 on 2023-12-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packerman', '0009_alter_event_item_unpacked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_item',
            name='unpacked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unpacking_user', to='packerman.user'),
        ),
        migrations.AlterField(
            model_name='user_item',
            name='item_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packerman.item'),
        ),
        migrations.AlterField(
            model_name='user_item',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='packerman.user'),
        ),
    ]
