# Generated by Django 4.2.7 on 2023-12-01 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packerman', '0010_alter_event_item_unpacked_by_alter_user_item_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_item',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='packerman.item'),
        ),
    ]
