# Generated by Django 4.2.7 on 2023-12-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packerman', '0011_alter_user_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_item',
            name='item_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='packerman.item'),
        ),
        migrations.AlterField(
            model_name='user_item',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='packerman.user'),
        ),
    ]
